### ISSUE TITLE
Do you need help maintaining this project?

### ISSUE THREAD

**Issue by palafoxernesto** [ACloudGuru/serverless-plugin-aws-alerts#111]
# This is a Proposal

Hi guys 👋! First of all I want to thank you for the time you devoted to make and maintain this plugin. I've found it very useful and, as far as I could search, there is no other plugin similar. 

At the same time, I can see a lot of unanswered Issues, and some PR open for more than a month still with no reviews or comments form maintainers. I understand that you may have other priorities, and that's totally ok. Time is a scarce and valuable resource.

So, I am ready to spent some time on maintaining this repo if it is ok with you. Just let me know. cc: @bulkan @johncmckim Et Al. ))

Thanks for your time.

**Comment by martrik** [comment]
Hey @palafoxernesto ! I just discussed it with my manager and I've got the green light to release our private fork. I'll need to do some cleanup before that, but it could be ready by the end of next week. Perhaps it makes sense to wait for some days to see if we get an answer from the current maintainers?

**Comment by adikari** [comment]
Hi @palafoxernesto, I am a tech lead at acloudguru and am currently exploring how we could potentially manage some of our projects which we no longer actively maintain. We do realize that a lot of users are currently are using this project and appreciate your enthusiasm on maintaining this repo. Give us some time until we decide how we want to deal with this situation and will get back to you. We are exploring either transferring ownership of this repo or finding a maintainer. Thanks.

**Comment by martrik** [comment]
Hello @adikari , do you have any updates on this?

**Comment by adikari** [comment]
Sorry for the late reply. Unfortunately, the conversation did not go too far ahead due to other priorities within the organisation.
This plugin has active users and a community. So, I have decided that I will maintain this repository until a decision on what to do is made. 
I will start by merging the open PR's and get myself familiar with what's happening here. If needed after that, I will contact the community members for help maintaining the repo.
